//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticClient.LogisticService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CargoСategory", Namespace="http://schemas.datacontract.org/2004/07/LogisticService")]
    [System.SerializableAttribute()]
    public partial class CargoСategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddedСostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BlockedTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddedСost {
            get {
                return this.AddedСostField;
            }
            set {
                if ((this.AddedСostField.Equals(value) != true)) {
                    this.AddedСostField = value;
                    this.RaisePropertyChanged("AddedСost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] BlockedTypes {
            get {
                return this.BlockedTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockedTypesField, value) != true)) {
                    this.BlockedTypesField = value;
                    this.RaisePropertyChanged("BlockedTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/LogisticService")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Department[] DepartmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Department[] Departments {
            get {
                return this.DepartmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentsField, value) != true)) {
                    this.DepartmentsField = value;
                    this.RaisePropertyChanged("Departments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/LogisticService")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Way", Namespace="http://schemas.datacontract.org/2004/07/LogisticService")]
    [System.SerializableAttribute()]
    public partial class Way : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.City DestinationCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.City InitialCityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryType {
            get {
                return this.DeliveryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryTypeField, value) != true)) {
                    this.DeliveryTypeField = value;
                    this.RaisePropertyChanged("DeliveryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.City DestinationCity {
            get {
                return this.DestinationCityField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationCityField, value) != true)) {
                    this.DestinationCityField = value;
                    this.RaisePropertyChanged("DestinationCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.City InitialCity {
            get {
                return this.InitialCityField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialCityField, value) != true)) {
                    this.InitialCityField = value;
                    this.RaisePropertyChanged("InitialCity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/LogisticService")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Department DeliveryPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Road PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Department ReceivingPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Customer RecipientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentState {
            get {
                return this.CurrentStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentStateField, value) != true)) {
                    this.CurrentStateField = value;
                    this.RaisePropertyChanged("CurrentState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Department DeliveryPoint {
            get {
                return this.DeliveryPointField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryPointField, value) != true)) {
                    this.DeliveryPointField = value;
                    this.RaisePropertyChanged("DeliveryPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Road Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Department ReceivingPoint {
            get {
                return this.ReceivingPointField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivingPointField, value) != true)) {
                    this.ReceivingPointField = value;
                    this.RaisePropertyChanged("ReceivingPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Customer Recipient {
            get {
                return this.RecipientField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientField, value) != true)) {
                    this.RecipientField = value;
                    this.RaisePropertyChanged("Recipient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingCode {
            get {
                return this.TrackingCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingCodeField, value) != true)) {
                    this.TrackingCodeField = value;
                    this.RaisePropertyChanged("TrackingCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/LogisticService")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Passport PassportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatronymicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Passport Passport {
            get {
                return this.PassportField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportField, value) != true)) {
                    this.PassportField = value;
                    this.RaisePropertyChanged("Passport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic {
            get {
                return this.PatronymicField;
            }
            set {
                if ((object.ReferenceEquals(this.PatronymicField, value) != true)) {
                    this.PatronymicField = value;
                    this.RaisePropertyChanged("Patronymic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Road", Namespace="http://schemas.datacontract.org/2004/07/LogisticService")]
    [System.SerializableAttribute()]
    public partial class Road : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Node[] PathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Node[] Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Passport", Namespace="http://schemas.datacontract.org/2004/07/LogisticService")]
    [System.SerializableAttribute()]
    public partial class Passport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Series {
            get {
                return this.SeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesField, value) != true)) {
                    this.SeriesField = value;
                    this.RaisePropertyChanged("Series");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Node", Namespace="http://schemas.datacontract.org/2004/07/LogisticService")]
    [System.SerializableAttribute()]
    public partial class Node : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int No {
            get {
                return this.NoField;
            }
            set {
                if ((this.NoField.Equals(value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoadStatus", Namespace="http://schemas.datacontract.org/2004/07/LogisticService")]
    [System.SerializableAttribute()]
    public partial class RoadStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeBeginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Department[] DestinationCityDepartmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Department[] InitialCityDepartmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitialCityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Department OrderBeginDepartmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogisticClient.LogisticService.Department OrderFinishDepartmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VisitStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentState {
            get {
                return this.CurrentStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentStateField, value) != true)) {
                    this.CurrentStateField = value;
                    this.RaisePropertyChanged("CurrentState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeBegin {
            get {
                return this.DateTimeBeginField;
            }
            set {
                if ((this.DateTimeBeginField.Equals(value) != true)) {
                    this.DateTimeBeginField = value;
                    this.RaisePropertyChanged("DateTimeBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeEnd {
            get {
                return this.DateTimeEndField;
            }
            set {
                if ((this.DateTimeEndField.Equals(value) != true)) {
                    this.DateTimeEndField = value;
                    this.RaisePropertyChanged("DateTimeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCity {
            get {
                return this.DestinationCityField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationCityField, value) != true)) {
                    this.DestinationCityField = value;
                    this.RaisePropertyChanged("DestinationCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Department[] DestinationCityDepartments {
            get {
                return this.DestinationCityDepartmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationCityDepartmentsField, value) != true)) {
                    this.DestinationCityDepartmentsField = value;
                    this.RaisePropertyChanged("DestinationCityDepartments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Department[] InitialCityDepartments {
            get {
                return this.InitialCityDepartmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialCityDepartmentsField, value) != true)) {
                    this.InitialCityDepartmentsField = value;
                    this.RaisePropertyChanged("InitialCityDepartments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitialCityName {
            get {
                return this.InitialCityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialCityNameField, value) != true)) {
                    this.InitialCityNameField = value;
                    this.RaisePropertyChanged("InitialCityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Department OrderBeginDepartments {
            get {
                return this.OrderBeginDepartmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderBeginDepartmentsField, value) != true)) {
                    this.OrderBeginDepartmentsField = value;
                    this.RaisePropertyChanged("OrderBeginDepartments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogisticClient.LogisticService.Department OrderFinishDepartments {
            get {
                return this.OrderFinishDepartmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderFinishDepartmentsField, value) != true)) {
                    this.OrderFinishDepartmentsField = value;
                    this.RaisePropertyChanged("OrderFinishDepartments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((this.SerialNumberField.Equals(value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VisitStatus {
            get {
                return this.VisitStatusField;
            }
            set {
                if ((this.VisitStatusField.Equals(value) != true)) {
                    this.VisitStatusField = value;
                    this.RaisePropertyChanged("VisitStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogisticService.ILogisticService", CallbackContract=typeof(LogisticClient.LogisticService.ILogisticServiceCallback))]
    public interface ILogisticService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/Connect", ReplyAction="http://tempuri.org/ILogisticService/ConnectResponse")]
        int Connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/Connect", ReplyAction="http://tempuri.org/ILogisticService/ConnectResponse")]
        System.Threading.Tasks.Task<int> ConnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/Disconnect", ReplyAction="http://tempuri.org/ILogisticService/DisconnectResponse")]
        void Disconnect(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/Disconnect", ReplyAction="http://tempuri.org/ILogisticService/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/Query", ReplyAction="http://tempuri.org/ILogisticService/QueryResponse")]
        void Query(int id, [System.ServiceModel.MessageParameterAttribute(Name="query")] string query1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/Query", ReplyAction="http://tempuri.org/ILogisticService/QueryResponse")]
        System.Threading.Tasks.Task QueryAsync(int id, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetCargoСategories", ReplyAction="http://tempuri.org/ILogisticService/GetCargoСategoriesResponse")]
        LogisticClient.LogisticService.CargoСategory[] GetCargoСategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetCargoСategories", ReplyAction="http://tempuri.org/ILogisticService/GetCargoСategoriesResponse")]
        System.Threading.Tasks.Task<LogisticClient.LogisticService.CargoСategory[]> GetCargoСategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetCity", ReplyAction="http://tempuri.org/ILogisticService/GetCityResponse")]
        LogisticClient.LogisticService.City GetCity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetCity", ReplyAction="http://tempuri.org/ILogisticService/GetCityResponse")]
        System.Threading.Tasks.Task<LogisticClient.LogisticService.City> GetCityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetWays", ReplyAction="http://tempuri.org/ILogisticService/GetWaysResponse")]
        LogisticClient.LogisticService.Way[] GetWays();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetWays", ReplyAction="http://tempuri.org/ILogisticService/GetWaysResponse")]
        System.Threading.Tasks.Task<LogisticClient.LogisticService.Way[]> GetWaysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/AddOrder", ReplyAction="http://tempuri.org/ILogisticService/AddOrderResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="orderID")]
        int AddOrder(LogisticClient.LogisticService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/AddOrder", ReplyAction="http://tempuri.org/ILogisticService/AddOrderResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="orderID")]
        System.Threading.Tasks.Task<int> AddOrderAsync(LogisticClient.LogisticService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/AddFullOrder", ReplyAction="http://tempuri.org/ILogisticService/AddFullOrderResponse")]
        void AddFullOrder(LogisticClient.LogisticService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/AddFullOrder", ReplyAction="http://tempuri.org/ILogisticService/AddFullOrderResponse")]
        System.Threading.Tasks.Task AddFullOrderAsync(LogisticClient.LogisticService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetRoadStatuses", ReplyAction="http://tempuri.org/ILogisticService/GetRoadStatusesResponse")]
        LogisticClient.LogisticService.RoadStatus[] GetRoadStatuses(string trakingCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetRoadStatuses", ReplyAction="http://tempuri.org/ILogisticService/GetRoadStatusesResponse")]
        System.Threading.Tasks.Task<LogisticClient.LogisticService.RoadStatus[]> GetRoadStatusesAsync(string trakingCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/IsRightAnswer", ReplyAction="http://tempuri.org/ILogisticService/IsRightAnswerResponse")]
        bool IsRightAnswer(string trakingCode, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/IsRightAnswer", ReplyAction="http://tempuri.org/ILogisticService/IsRightAnswerResponse")]
        System.Threading.Tasks.Task<bool> IsRightAnswerAsync(string trakingCode, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/UpdateOrderStatus", ReplyAction="http://tempuri.org/ILogisticService/UpdateOrderStatusResponse")]
        void UpdateOrderStatus(string trakingCode, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/UpdateOrderStatus", ReplyAction="http://tempuri.org/ILogisticService/UpdateOrderStatusResponse")]
        System.Threading.Tasks.Task UpdateOrderStatusAsync(string trakingCode, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetCurrentProfit", ReplyAction="http://tempuri.org/ILogisticService/GetCurrentProfitResponse")]
        int GetCurrentProfit(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetCurrentProfit", ReplyAction="http://tempuri.org/ILogisticService/GetCurrentProfitResponse")]
        System.Threading.Tasks.Task<int> GetCurrentProfitAsync(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetExpectedProfit", ReplyAction="http://tempuri.org/ILogisticService/GetExpectedProfitResponse")]
        int GetExpectedProfit(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetExpectedProfit", ReplyAction="http://tempuri.org/ILogisticService/GetExpectedProfitResponse")]
        System.Threading.Tasks.Task<int> GetExpectedProfitAsync(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetOrderNumber", ReplyAction="http://tempuri.org/ILogisticService/GetOrderNumberResponse")]
        int GetOrderNumber(System.DateTime start, System.DateTime end, string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogisticService/GetOrderNumber", ReplyAction="http://tempuri.org/ILogisticService/GetOrderNumberResponse")]
        System.Threading.Tasks.Task<int> GetOrderNumberAsync(System.DateTime start, System.DateTime end, string state);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogisticServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILogisticService/QueryCallback")]
        void QueryCallback(string answer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogisticServiceChannel : LogisticClient.LogisticService.ILogisticService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogisticServiceClient : System.ServiceModel.DuplexClientBase<LogisticClient.LogisticService.ILogisticService>, LogisticClient.LogisticService.ILogisticService {
        
        public LogisticServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LogisticServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LogisticServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LogisticServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LogisticServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int Connect() {
            return base.Channel.Connect();
        }
        
        public System.Threading.Tasks.Task<int> ConnectAsync() {
            return base.Channel.ConnectAsync();
        }
        
        public void Disconnect(int id) {
            base.Channel.Disconnect(id);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(int id) {
            return base.Channel.DisconnectAsync(id);
        }
        
        public void Query(int id, string query1) {
            base.Channel.Query(id, query1);
        }
        
        public System.Threading.Tasks.Task QueryAsync(int id, string query) {
            return base.Channel.QueryAsync(id, query);
        }
        
        public LogisticClient.LogisticService.CargoСategory[] GetCargoСategories() {
            return base.Channel.GetCargoСategories();
        }
        
        public System.Threading.Tasks.Task<LogisticClient.LogisticService.CargoСategory[]> GetCargoСategoriesAsync() {
            return base.Channel.GetCargoСategoriesAsync();
        }
        
        public LogisticClient.LogisticService.City GetCity() {
            return base.Channel.GetCity();
        }
        
        public System.Threading.Tasks.Task<LogisticClient.LogisticService.City> GetCityAsync() {
            return base.Channel.GetCityAsync();
        }
        
        public LogisticClient.LogisticService.Way[] GetWays() {
            return base.Channel.GetWays();
        }
        
        public System.Threading.Tasks.Task<LogisticClient.LogisticService.Way[]> GetWaysAsync() {
            return base.Channel.GetWaysAsync();
        }
        
        public int AddOrder(LogisticClient.LogisticService.Order order) {
            return base.Channel.AddOrder(order);
        }
        
        public System.Threading.Tasks.Task<int> AddOrderAsync(LogisticClient.LogisticService.Order order) {
            return base.Channel.AddOrderAsync(order);
        }
        
        public void AddFullOrder(LogisticClient.LogisticService.Order order) {
            base.Channel.AddFullOrder(order);
        }
        
        public System.Threading.Tasks.Task AddFullOrderAsync(LogisticClient.LogisticService.Order order) {
            return base.Channel.AddFullOrderAsync(order);
        }
        
        public LogisticClient.LogisticService.RoadStatus[] GetRoadStatuses(string trakingCode) {
            return base.Channel.GetRoadStatuses(trakingCode);
        }
        
        public System.Threading.Tasks.Task<LogisticClient.LogisticService.RoadStatus[]> GetRoadStatusesAsync(string trakingCode) {
            return base.Channel.GetRoadStatusesAsync(trakingCode);
        }
        
        public bool IsRightAnswer(string trakingCode, string phoneNumber) {
            return base.Channel.IsRightAnswer(trakingCode, phoneNumber);
        }
        
        public System.Threading.Tasks.Task<bool> IsRightAnswerAsync(string trakingCode, string phoneNumber) {
            return base.Channel.IsRightAnswerAsync(trakingCode, phoneNumber);
        }
        
        public void UpdateOrderStatus(string trakingCode, string status) {
            base.Channel.UpdateOrderStatus(trakingCode, status);
        }
        
        public System.Threading.Tasks.Task UpdateOrderStatusAsync(string trakingCode, string status) {
            return base.Channel.UpdateOrderStatusAsync(trakingCode, status);
        }
        
        public int GetCurrentProfit(System.DateTime start, System.DateTime end) {
            return base.Channel.GetCurrentProfit(start, end);
        }
        
        public System.Threading.Tasks.Task<int> GetCurrentProfitAsync(System.DateTime start, System.DateTime end) {
            return base.Channel.GetCurrentProfitAsync(start, end);
        }
        
        public int GetExpectedProfit(System.DateTime start, System.DateTime end) {
            return base.Channel.GetExpectedProfit(start, end);
        }
        
        public System.Threading.Tasks.Task<int> GetExpectedProfitAsync(System.DateTime start, System.DateTime end) {
            return base.Channel.GetExpectedProfitAsync(start, end);
        }
        
        public int GetOrderNumber(System.DateTime start, System.DateTime end, string state) {
            return base.Channel.GetOrderNumber(start, end, state);
        }
        
        public System.Threading.Tasks.Task<int> GetOrderNumberAsync(System.DateTime start, System.DateTime end, string state) {
            return base.Channel.GetOrderNumberAsync(start, end, state);
        }
    }
}
